-- Prime Origins Atlas — credit inventory
--
-- Run this once in the Supabase SQL editor for the Atlas project.
-- It is idempotent: safe to re-run.
--
-- Design note: availability is DERIVED, never stored.
--   available = tonnes_total - tonnes_sold - (live, unexpired holds)
-- Storing an "available" column invites drift between it and reality; deriving
-- it means an abandoned checkout self-heals when its hold expires, with no
-- cleanup job to forget about.

-- ---------------------------------------------------------------- inventory
create table if not exists inventory (
  listing_id   text primary key,
  tonnes_total integer not null check (tonnes_total >= 0),
  tonnes_sold  integer not null default 0 check (tonnes_sold >= 0),
  updated_at   timestamptz not null default now()
);

-- Deliberately NO check that tonnes_sold <= tonnes_total. If a payment somehow
-- lands against an expired hold we must still record the money; refusing to
-- write it would be worse than briefly showing a negative margin. The webhook
-- flags any such case in the admin email instead.

-- ------------------------------------------------------------- reservations
-- id is generated by the app BEFORE the Stripe session exists, so the hold is
-- taken before we ever create something the buyer could pay for.
create table if not exists reservations (
  id                text primary key,
  listing_id        text not null references inventory(listing_id) on delete cascade,
  tonnes            integer not null check (tonnes > 0),
  status            text not null default 'held' check (status in ('held', 'confirmed', 'released')),
  stripe_session_id text unique,
  expires_at        timestamptz not null,
  created_at        timestamptz not null default now(),
  confirmed_at      timestamptz
);

create index if not exists reservations_live_idx
  on reservations (listing_id, status, expires_at);

-- ------------------------------------------------------------- availability
create or replace function available_tonnes(p_listing_id text)
returns integer
language sql
stable
as $$
  select greatest(
    0,
    i.tonnes_total - i.tonnes_sold - coalesce((
      select sum(r.tonnes)
      from reservations r
      where r.listing_id = i.listing_id
        and r.status = 'held'
        and r.expires_at > now()
    ), 0)
  )::integer
  from inventory i
  where i.listing_id = p_listing_id;
$$;

-- ------------------------------------------------------------------ reserve
-- The whole point of this file. SELECT ... FOR UPDATE serialises every
-- concurrent checkout for the same listing, so two buyers cannot both pass the
-- availability check and both get a hold.
create or replace function reserve_tonnes(
  p_id          text,
  p_listing_id  text,
  p_tonnes      integer,
  p_ttl_minutes integer default 60
)
returns jsonb
language plpgsql
as $$
declare
  v_total     integer;
  v_sold      integer;
  v_held      integer;
  v_available integer;
begin
  select tonnes_total, tonnes_sold
    into v_total, v_sold
    from inventory
   where listing_id = p_listing_id
     for update;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'unknown_listing', 'available', 0);
  end if;

  select coalesce(sum(tonnes), 0)
    into v_held
    from reservations
   where listing_id = p_listing_id
     and status = 'held'
     and expires_at > now();

  v_available := greatest(0, v_total - v_sold - v_held);

  if p_tonnes > v_available then
    return jsonb_build_object('ok', false, 'reason', 'insufficient', 'available', v_available);
  end if;

  insert into reservations (id, listing_id, tonnes, expires_at)
  values (p_id, p_listing_id, p_tonnes, now() + make_interval(mins => p_ttl_minutes))
  on conflict (id) do update
    set tonnes     = excluded.tonnes,
        expires_at = excluded.expires_at,
        status     = 'held';

  return jsonb_build_object('ok', true, 'available', v_available - p_tonnes);
end;
$$;

-- ------------------------------------------------------------------ confirm
-- Called from the Stripe webhook once payment is real. Idempotent: Stripe
-- retries webhooks, and a retry must not sell the tonnes twice.
create or replace function confirm_reservation(p_id text)
returns jsonb
language plpgsql
as $$
declare
  r          reservations%rowtype;
  v_total    integer;
  v_new_sold integer;
begin
  select * into r from reservations where id = p_id for update;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'unknown_reservation');
  end if;

  if r.status = 'confirmed' then
    return jsonb_build_object('ok', true, 'already_confirmed', true, 'tonnes', r.tonnes);
  end if;

  update inventory
     set tonnes_sold = tonnes_sold + r.tonnes,
         updated_at  = now()
   where listing_id = r.listing_id
  returning tonnes_total, tonnes_sold into v_total, v_new_sold;

  update reservations
     set status       = 'confirmed',
         confirmed_at = now()
   where id = p_id;

  return jsonb_build_object(
    'ok', true,
    'already_confirmed', false,
    'tonnes', r.tonnes,
    'listing_id', r.listing_id,
    'expired_hold', r.expires_at <= now(),
    'oversold', v_new_sold > v_total
  );
end;
$$;

-- ------------------------------------------------------------------ release
create or replace function release_reservation(p_id text)
returns jsonb
language plpgsql
as $$
begin
  update reservations
     set status = 'released'
   where id = p_id
     and status = 'held';
  return jsonb_build_object('ok', found);
end;
$$;

-- ---------------------------------------------------------------------- RLS
-- Everything runs server-side with the service-role key, which bypasses RLS.
-- Enable RLS with no policies so an accidentally-leaked anon key reads nothing.
alter table inventory    enable row level security;
alter table reservations enable row level security;
