import type { Listing } from './types';

export const listings: Listing[] = [
  {
    id: 'po-001',
    slug: 'kasigau-corridor-redd',
    projectName: 'Kasigau Corridor REDD+',
    developer: 'Wildlife Works',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0009 — Avoided Deforestation',
    projectId: 'VCS-562',
    vintage: 2023,
    country: 'Kenya',
    region: 'Taita Taveta',
    pricePerTonne: 14.5,
    tonnesAvailable: 25000,
    totalIssued: 1450000,
    bufferPoolPct: 20,
    cobenefits: ['Biodiversity', 'Community livelihoods', 'Wildlife corridor protection'],
    sdgs: [1, 8, 13, 15],
    summary: 'Protects 200,000 hectares of dryland forest between two Kenyan national parks while employing 350+ local rangers.',
    description:
      'The Kasigau Corridor REDD+ project safeguards a vital wildlife migration route connecting Tsavo East and Tsavo West National Parks. The project has reduced deforestation by over 95% in the project area and supports more than 100,000 community members through education, water, and livelihoods programs.',
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true,
    featured: true
  },
  {
    id: 'po-002',
    slug: 'climeworks-orca-dac',
    projectName: 'Orca Direct Air Capture',
    developer: 'Climeworks',
    category: 'engineered-removal',
    registry: 'Puro.earth',
    methodology: 'Geological Storage (Carbfix)',
    projectId: 'PURO-DAC-001',
    vintage: 2025,
    country: 'Iceland',
    region: 'Hellisheidi',
    pricePerTonne: 685,
    tonnesAvailable: 1200,
    totalIssued: 4000,
    cobenefits: ['Permanent storage (>10,000 years)', 'Renewable-powered'],
    sdgs: [9, 13],
    summary: 'Durable removal credits from the world\'s first commercial direct air capture and storage facility.',
    description:
      'Orca captures CO₂ directly from the atmosphere using geothermal power and mineralizes it in basalt rock via Carbfix technology, achieving permanent storage. Issuance is verified under the Puro Standard for CO₂ Removal.',
    imageUrl: 'https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true,
    featured: true
  },
  {
    id: 'po-003',
    slug: 'gyapa-cookstoves-ghana',
    projectName: 'Gyapa Improved Cookstoves',
    developer: 'ClimateCare',
    category: 'community',
    registry: 'Gold Standard',
    methodology: 'GS TPDDTEC',
    projectId: 'GS-852',
    vintage: 2024,
    country: 'Ghana',
    pricePerTonne: 12.0,
    tonnesAvailable: 48000,
    totalIssued: 2100000,
    cobenefits: ['Indoor air quality', 'Women\'s livelihoods', 'Reduced fuelwood demand'],
    sdgs: [3, 5, 7, 13],
    summary: 'Efficient cookstoves cutting charcoal use 50%+ across Ghanaian households — better health, lower emissions.',
    description:
      'Gyapa distributes locally-made efficient cookstoves that reduce charcoal consumption by 50% or more compared to traditional stoves. The project has reached over 1 million households, with verified emissions reductions and significant indoor air quality improvements.',
    imageUrl: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-004',
    slug: 'mai-ndombe-redd',
    projectName: 'Mai Ndombe REDD+',
    developer: 'Wildlife Works',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0007 REDD+ MF',
    projectId: 'VCS-934',
    vintage: 2022,
    country: 'DR Congo',
    pricePerTonne: 11.0,
    tonnesAvailable: 95000,
    totalIssued: 8200000,
    bufferPoolPct: 22,
    cobenefits: ['Bonobo habitat protection', 'Community health clinics', 'Schools'],
    sdgs: [1, 3, 4, 13, 15],
    summary: 'Protects 300,000 ha of Congo Basin rainforest, home to bonobos and 50,000+ community members.',
    description:
      'One of the largest REDD+ projects in the world, Mai Ndombe protects critical rainforest in the Congo Basin while delivering health, education, and agricultural support to surrounding communities.',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-005',
    slug: 'pacific-biochar-california',
    projectName: 'Pacific Biochar Carbon Removal',
    developer: 'Pacific Biochar',
    category: 'engineered-removal',
    registry: 'Puro.earth',
    methodology: 'Puro Biochar Methodology v3',
    projectId: 'PURO-BIO-119',
    vintage: 2025,
    country: 'United States',
    region: 'California',
    pricePerTonne: 145,
    tonnesAvailable: 6500,
    totalIssued: 18000,
    cobenefits: ['Soil health', 'Wildfire fuel reduction', 'Agricultural yields'],
    sdgs: [2, 13, 15],
    summary: 'Forest residue converted to biochar — durable carbon storage in agricultural soils across the West Coast.',
    description:
      'Pacific Biochar converts forestry residues from wildfire fuel-reduction operations into stable biochar applied to California vineyards and orchards. Storage is durable on a >100-year timescale.',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true,
    featured: true
  },
  {
    id: 'po-006',
    slug: 'rimba-raya-borneo',
    projectName: 'Rimba Raya Biodiversity Reserve',
    developer: 'InfiniteEARTH',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0007 REDD+ MF',
    projectId: 'VCS-674',
    vintage: 2023,
    country: 'Indonesia',
    region: 'Central Kalimantan',
    pricePerTonne: 16.5,
    tonnesAvailable: 32000,
    totalIssued: 3800000,
    bufferPoolPct: 20,
    cobenefits: ['Orangutan habitat', 'Peatland protection', 'All 17 SDGs validated'],
    sdgs: [1, 2, 3, 4, 5, 13, 14, 15, 17],
    summary: 'Orangutan refuge on peatland in Borneo — the first project triple-validated under all 17 SDGs.',
    description:
      'Rimba Raya protects 64,000 hectares of carbon-rich tropical peatland, providing critical refuge for endangered Bornean orangutans while delivering measurable benefits across all 17 UN Sustainable Development Goals.',
    imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-007',
    slug: 'gujarat-wind-india',
    projectName: 'Gujarat Wind Power',
    developer: 'Suzlon Global',
    category: 'renewable-energy',
    registry: 'Gold Standard',
    methodology: 'GS Renewable Energy v2',
    projectId: 'GS-1142',
    vintage: 2024,
    country: 'India',
    region: 'Gujarat',
    pricePerTonne: 4.8,
    tonnesAvailable: 120000,
    totalIssued: 950000,
    cobenefits: ['Rural electrification', 'Local employment'],
    sdgs: [7, 8, 13],
    summary: 'Grid-connected wind farm displacing coal generation in western India.',
    description:
      'A 200 MW wind installation in Gujarat displacing emissions from the predominantly coal-fueled Indian grid. Gold Standard certified with verified community impact.',
    imageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-008',
    slug: 'running-tide-kelp',
    projectName: 'Running Tide Ocean Carbon',
    developer: 'Running Tide',
    category: 'engineered-removal',
    registry: 'Puro.earth',
    methodology: 'Ocean Alkalinity & Biomass Sinking',
    projectId: 'PURO-OCN-042',
    vintage: 2025,
    country: 'Iceland',
    pricePerTonne: 240,
    tonnesAvailable: 3200,
    totalIssued: 9500,
    cobenefits: ['Ocean alkalinity restoration', 'Deep-sea storage'],
    sdgs: [13, 14],
    summary: 'Macroalgae-based ocean carbon removal with deep-sea sinking for durable storage.',
    description:
      'Running Tide grows macroalgae on biodegradable buoys seeded with alkaline limestone. The buoys sink to the deep ocean where carbon is stored on multi-century timescales while restoring ocean chemistry.',
    imageUrl: 'https://images.unsplash.com/photo-1530053969600-caed2596d242?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-009',
    slug: 'amazonia-pariri',
    projectName: 'Pariri Amazon Conservation',
    developer: 'Carbonext',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0015',
    projectId: 'VCS-2613',
    vintage: 2024,
    country: 'Brazil',
    region: 'Pará',
    pricePerTonne: 13.2,
    tonnesAvailable: 41000,
    totalIssued: 6700000,
    bufferPoolPct: 25,
    cobenefits: ['Indigenous land rights', 'Açaí economy', 'Jaguar habitat'],
    sdgs: [1, 10, 13, 15],
    summary: 'Indigenous-led Amazon conservation across 350,000+ hectares of primary rainforest.',
    description:
      'The Pariri project is co-developed with the Munduruku people, protecting one of the most biodiverse regions of the Brazilian Amazon while supporting traditional livelihoods.',
    imageUrl: 'https://images.unsplash.com/photo-1500354960784-987d10b03d22?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-010',
    slug: 'cquestr8-rock-weathering',
    projectName: 'Enhanced Rock Weathering — UK Croplands',
    developer: 'UNDO',
    category: 'engineered-removal',
    registry: 'Puro.earth',
    methodology: 'Enhanced Weathering of Silicate Minerals',
    projectId: 'PURO-ERW-014',
    vintage: 2025,
    country: 'United Kingdom',
    region: 'Scotland',
    pricePerTonne: 195,
    tonnesAvailable: 4800,
    totalIssued: 14000,
    cobenefits: ['Soil pH improvement', 'Crop yield', 'Reduced fertilizer use'],
    sdgs: [2, 13, 15],
    summary: 'Crushed basalt spread on UK farmland sequesters CO₂ as it weathers — 10,000+ year storage.',
    description:
      'UNDO spreads finely-crushed basalt on agricultural land. As the rock weathers naturally, it draws CO₂ from the atmosphere and locks it away as stable bicarbonate. Co-benefits include soil de-acidification and improved yields.',
    imageUrl: 'https://images.unsplash.com/photo-1535912559178-bb46760ad0fa?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-011',
    slug: 'methane-capture-landfill-texas',
    projectName: 'McCommas Bluff Landfill Methane Capture',
    developer: 'EDF Renewables',
    category: 'renewable-energy',
    registry: 'ACR',
    methodology: 'ACR Landfill Gas Destruction v1.1',
    projectId: 'ACR-380',
    vintage: 2024,
    country: 'United States',
    region: 'Texas',
    pricePerTonne: 7.5,
    tonnesAvailable: 28000,
    totalIssued: 410000,
    cobenefits: ['Methane abatement', 'Renewable natural gas'],
    sdgs: [7, 11, 13],
    summary: 'Captures methane from a Dallas landfill — converted to renewable natural gas for the grid.',
    description:
      'Methane (28× more potent than CO₂ on a 100-year basis) is captured from the McCommas Bluff landfill and converted into renewable natural gas, displacing fossil natural gas demand.',
    imageUrl: 'https://images.unsplash.com/photo-1473773386757-42beed09bb7b?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-013',
    slug: 'sussex-regen-farm',
    projectName: 'Sussex Regenerative Farm — Soil Carbon Pilot',
    developer: 'Downsview Farm Co-operative',
    category: 'nature-based',
    registry: 'Self-Verified',
    methodology: 'IPCC Tier 1 + soil sampling protocol',
    projectId: 'POA-SV-013',
    vintage: 2025,
    country: 'United Kingdom',
    region: 'East Sussex',
    pricePerTonne: 28.0,
    tonnesAvailable: 1200,
    totalIssued: 1800,
    cobenefits: ['Soil health', 'Biodiversity uplift', 'Local sourcing'],
    sdgs: [2, 13, 15],
    summary: 'Cover cropping and reduced tillage across 320 ha of arable land — third-party soil sampling included.',
    description:
      'A co-operative of three farms in the South Downs implementing cover crops, reduced-tillage and rotational grazing. Soil carbon is sampled annually by an independent UK lab. Self-verified credits — full sampling reports and methodology disclosed below.',
    imageUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'self-verified',
    retirementSupported: true,
    latitude: 50.85,
    longitude: 0.10,
    documents: [
      { label: 'Soil sampling report (2025)', url: 'https://example.com/sussex-soil-2025.pdf', filename: 'sussex-soil-2025.pdf' },
      { label: 'Methodology disclosure', url: 'https://example.com/sussex-methodology.pdf', filename: 'sussex-methodology.pdf' },
      { label: 'Independent lab COA', url: 'https://example.com/sussex-coa.pdf', filename: 'sussex-coa.pdf' }
    ]
  },
  {
    id: 'po-014',
    slug: 'kerala-smallholder-agroforestry',
    projectName: 'Kerala Smallholder Agroforestry',
    developer: 'WaynaCarbon Co-op',
    category: 'nature-based',
    registry: 'Self-Verified',
    methodology: 'CDM AR-AMS0007 (adapted)',
    projectId: 'POA-SV-014',
    vintage: 2024,
    country: 'India',
    region: 'Wayanad, Kerala',
    pricePerTonne: 19.5,
    tonnesAvailable: 3400,
    totalIssued: 4200,
    cobenefits: ['Smallholder income', 'Forest cover', 'Watershed protection'],
    sdgs: [1, 13, 15],
    summary: '420 smallholder farms intercropping native species with coffee and spices — biomass tracked annually.',
    description:
      'A self-verified agroforestry programme covering 420 smallholder plots in Wayanad. Tree biomass is measured annually using allometric equations adapted from CDM AR-AMS0007. Verification documentation is provided directly by the co-operative.',
    imageUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'self-verified',
    retirementSupported: true,
    latitude: 11.69,
    longitude: 76.13,
    documents: [
      { label: 'Biomass measurement report', url: 'https://example.com/kerala-biomass.pdf', filename: 'kerala-biomass.pdf' },
      { label: 'Co-operative member list & plot boundaries', url: 'https://example.com/kerala-plots.pdf', filename: 'kerala-plots.pdf' }
    ]
  },
  {
    id: 'po-012',
    slug: 'mangrove-restoration-philippines',
    projectName: 'Visayas Mangrove Restoration',
    developer: 'WorldView Impact',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0033 Tidal Wetland Restoration',
    projectId: 'VCS-2876',
    vintage: 2024,
    country: 'Philippines',
    region: 'Eastern Visayas',
    pricePerTonne: 21.0,
    tonnesAvailable: 8500,
    totalIssued: 145000,
    bufferPoolPct: 30,
    cobenefits: ['Coastal protection', 'Fisheries recovery', 'Typhoon resilience'],
    sdgs: [1, 13, 14, 15],
    summary: 'Restored mangrove forests sequester carbon at high rates while protecting coastal communities.',
    description:
      'Replanting and protecting 2,400 hectares of mangrove forest in typhoon-prone coastal communities. Blue carbon storage rates 3-5× higher per hectare than terrestrial forests.',
    imageUrl: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true,
    featured: true
  },
  {
    id: 'po-015',
    slug: 'katingan-mentaya-peatland',
    projectName: 'Katingan Mentaya Peatland Conservation',
    developer: 'PT Rimba Makmur Utama',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0007 REDD+ MF',
    projectId: 'VCS-1477',
    vintage: 2024,
    country: 'Indonesia',
    region: 'Central Kalimantan',
    pricePerTonne: 18.0,
    tonnesAvailable: 75000,
    totalIssued: 30000000,
    bufferPoolPct: 22,
    cobenefits: ['Orangutan habitat', 'Peatland fire prevention', 'Indigenous Dayak livelihoods'],
    sdgs: [1, 13, 14, 15, 17],
    summary: 'Protects 149,800 ha of deep tropical peatland — one of the largest peat-swamp REDD+ projects in the world.',
    description:
      'The Katingan Mentaya project conserves a vast peat-swamp ecosystem in Central Kalimantan, preventing the release of an estimated 7.5 million tCO₂e per year through avoided drainage and fire. The project is independently rated and partners with surrounding Dayak communities on agroforestry and small-business livelihoods.',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-016',
    slug: 'keo-seima-wildlife-sanctuary',
    projectName: 'Keo Seima Wildlife Sanctuary REDD+',
    developer: 'Wildlife Conservation Society',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0007 REDD+ MF',
    projectId: 'VCS-1650',
    vintage: 2024,
    country: 'Cambodia',
    region: 'Mondulkiri',
    pricePerTonne: 19.5,
    tonnesAvailable: 22000,
    totalIssued: 2100000,
    bufferPoolPct: 25,
    cobenefits: ['Bunong indigenous land rights', 'Yellow-cheeked gibbon habitat', 'CCB Gold'],
    sdgs: [1, 10, 13, 15],
    summary: 'WCS-operated REDD+ in eastern Cambodia — protects 166,983 ha for the indigenous Bunong people and 75 threatened species.',
    description:
      'Keo Seima protects mosaic forest landscapes that are home to the indigenous Bunong people and globally important biodiversity including yellow-cheeked crested gibbons. Triple-validated under CCB Gold for climate, community and biodiversity.',
    imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true,
    featured: true
  },
  {
    id: 'po-017',
    slug: 'tambopata-bahuaja',
    projectName: 'Tambopata-Bahuaja Biodiversity Reserve',
    developer: 'AIDER / Bosques Amazónicos',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0007 REDD+ MF',
    projectId: 'VCS-1067',
    vintage: 2023,
    country: 'Peru',
    region: 'Madre de Dios',
    pricePerTonne: 15.0,
    tonnesAvailable: 31000,
    totalIssued: 4900000,
    bufferPoolPct: 20,
    cobenefits: ['Brazil-nut agroforestry', 'Jaguar & giant otter habitat', '400+ bird species'],
    sdgs: [1, 8, 13, 15],
    summary: 'Buffer-zone REDD+ around two flagship Peruvian Amazon reserves, scaling sustainable Brazil-nut harvesting.',
    description:
      'Tambopata-Bahuaja protects 573,000 hectares of buffer zone around two of Peru\'s most biodiverse national parks. The project pioneered the Brazil-nut agroforestry model that gives local concessionaires a forest-positive livelihood.',
    imageUrl: 'https://images.unsplash.com/photo-1500354960784-987d10b03d22?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-018',
    slug: 'envira-amazonia-acre',
    projectName: 'Envira Amazonia',
    developer: 'CarbonCo / Carbon Securities',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0015',
    projectId: 'VCS-1382',
    vintage: 2024,
    country: 'Brazil',
    region: 'Acre',
    pricePerTonne: 13.5,
    tonnesAvailable: 38000,
    totalIssued: 12500000,
    bufferPoolPct: 22,
    cobenefits: ['Smallholder smallholder agreements', 'Açaí & Brazil-nut economy', 'CCB Triple Gold'],
    sdgs: [1, 8, 13, 15],
    summary: 'CCB Triple Gold REDD+ project in the Brazilian state of Acre — 39,300 ha of Amazon rainforest under protection.',
    description:
      'Envira Amazonia is a CCB Triple Gold (climate, community, biodiversity) project protecting Amazon rainforest in Acre and providing alternative livelihoods to smallholders through sustainable harvesting agreements.',
    imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-019',
    slug: 'uganda-cookstoves',
    projectName: 'Uganda Improved Cookstoves',
    developer: 'Community Carbon (Carbon Streaming)',
    category: 'community',
    registry: 'Gold Standard',
    methodology: 'GS TPDDTEC',
    projectId: 'GS-10967',
    vintage: 2024,
    country: 'Uganda',
    pricePerTonne: 10.5,
    tonnesAvailable: 65000,
    totalIssued: 1450000,
    cobenefits: ['Indoor air quality', 'Women\'s time savings', 'Reduced biomass demand'],
    sdgs: [3, 5, 7, 13, 15],
    summary: 'Fuel-efficient cookstoves distributed across Ugandan households, cutting biomass use 40-60%.',
    description:
      'A large-scale Programme of Activities distributing improved cookstoves across Uganda. Reduces fuelwood demand, indoor air pollution, and women\'s daily collection time. Gold Standard certified with verified emissions reductions.',
    imageUrl: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-020',
    slug: 'mozambique-cookstoves',
    projectName: 'Mozambique Improved Cookstoves',
    developer: 'Community Carbon (Carbon Streaming)',
    category: 'community',
    registry: 'Gold Standard',
    methodology: 'GS TPDDTEC',
    projectId: 'GS-11211',
    vintage: 2024,
    country: 'Mozambique',
    pricePerTonne: 11.5,
    tonnesAvailable: 42000,
    totalIssued: 880000,
    cobenefits: ['Indoor air quality', 'Women\'s livelihoods', 'Forest pressure reduction'],
    sdgs: [3, 5, 7, 13],
    summary: 'Programme deploying clean cookstoves across Mozambican communities — verified under Gold Standard.',
    description:
      'Distribution of efficient cookstoves to households across Mozambique, paired with monitoring of usage rates and biomass consumption. Issuance under Gold Standard\'s technology-and-practice methodology.',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-021',
    slug: 'malawi-water-filters',
    projectName: 'Malawi Safe Water Filters',
    developer: 'Community Carbon (Carbon Streaming)',
    category: 'community',
    registry: 'Gold Standard',
    methodology: 'GS Safe Water Supply',
    projectId: 'GS-11245',
    vintage: 2024,
    country: 'Malawi',
    pricePerTonne: 13.0,
    tonnesAvailable: 18000,
    totalIssued: 240000,
    cobenefits: ['Waterborne disease reduction', 'Avoided wood-fuel boiling', 'Women & children\'s health'],
    sdgs: [3, 6, 13],
    summary: 'Household water purification devices that displace wood-fuel boiling — health + emissions co-benefits.',
    description:
      'Distribution of household water filters that remove pathogens without the need for boiling, cutting both fuelwood demand and waterborne illness. Issued under Gold Standard\'s Safe Water Supply methodology.',
    imageUrl: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-022',
    slug: 'fasera-biomass-storage-australia',
    projectName: 'Fasera Terrestrial Biomass Storage',
    developer: 'Fasera',
    category: 'engineered-removal',
    registry: 'Puro.earth',
    methodology: 'Terrestrial Biomass Storage',
    projectId: 'PURO-TBS-007',
    vintage: 2025,
    country: 'Australia',
    region: 'New South Wales',
    pricePerTonne: 175,
    tonnesAvailable: 2200,
    totalIssued: 8400,
    cobenefits: ['Wildfire fuel reduction', 'Soil carbon enhancement', 'Permanent storage (>100 yrs)'],
    sdgs: [13, 15],
    summary: 'Engineered biomass burial in oxygen-free underground vaults — durable CO₂ removal certified by Puro.earth.',
    description:
      'Fasera takes residual woody biomass and stores it in engineered, oxygen-free underground vaults that prevent decay and methane release. The Puro Terrestrial Biomass Storage methodology certifies storage durability on a >100-year timescale.',
    imageUrl: 'https://images.unsplash.com/photo-1574263867128-b94beea1dee5?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-023',
    slug: 'california-soil-enrichment',
    projectName: 'Central Valley Soil Enrichment Programme',
    developer: 'Indigo Ag',
    category: 'nature-based',
    registry: 'Climate Action Reserve',
    methodology: 'Soil Enrichment Protocol v1.1',
    projectId: 'CAR-1419',
    vintage: 2024,
    country: 'United States',
    region: 'California',
    pricePerTonne: 32.0,
    tonnesAvailable: 9500,
    totalIssued: 75000,
    bufferPoolPct: 20,
    cobenefits: ['Soil organic matter increase', 'Water retention', 'Reduced synthetic inputs'],
    sdgs: [2, 13, 15],
    summary: 'CCP-eligible soil-carbon credits from regenerative practices on Central Valley cropland.',
    description:
      'Multi-farm soil enrichment programme implementing cover crops, reduced tillage, and nutrient-management changes across cropland in California\'s Central Valley. Issued under CAR\'s Soil Enrichment Protocol — CCP-eligible for 2026.',
    imageUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  },
  {
    id: 'po-024',
    slug: 'sierra-madre-mexico-forest',
    projectName: 'Sierra Madre Community Forest Protocol',
    developer: 'Pronatura México',
    category: 'nature-based',
    registry: 'Climate Action Reserve',
    methodology: 'Mexico Forest Protocol v3.0',
    projectId: 'CAR-MXF-088',
    vintage: 2024,
    country: 'Mexico',
    region: 'Jalisco',
    pricePerTonne: 17.5,
    tonnesAvailable: 14000,
    totalIssued: 320000,
    bufferPoolPct: 22,
    cobenefits: ['Ejido community land tenure', 'Watershed protection', 'Endemic species'],
    sdgs: [1, 10, 13, 15],
    summary: 'Community-managed forest carbon in Mexico\'s Sierra Madre Occidental, under CAR\'s CCP-approved protocol.',
    description:
      'Improved forest management across communal "ejido" lands in the Sierra Madre Occidental of Jalisco. Combines selective harvesting with conservation set-asides. Issued under CAR\'s Mexico Forest Protocol v3.0 — CCP-approved with conditions in 2026.',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    tier: 'prime-origins-verified',
    retirementSupported: true
  }
];

// Add latitude/longitude to a few listings so the map is populated for the demo
const coords: Record<string, [number, number]> = {
  'po-001': [-3.85, 38.65],     // Kasigau, Kenya
  'po-002': [64.05, -21.40],    // Hellisheidi, Iceland
  'po-003': [7.95, -1.03],      // Ghana centroid
  'po-004': [-2.50, 18.30],     // Mai Ndombe, DRC
  'po-005': [38.50, -121.50],   // California
  'po-006': [-2.65, 112.50],    // Central Kalimantan, Borneo
  'po-007': [22.30, 71.20],     // Gujarat, India
  'po-008': [64.13, -21.95],    // Iceland
  'po-009': [-3.50, -52.50],    // Pará, Brazil
  'po-010': [56.50, -4.20],     // Scotland
  'po-011': [32.65, -96.70],    // Dallas
  'po-012': [11.50, 125.00],    // Eastern Visayas, Philippines
  'po-015': [-2.07, 113.30],    // Katingan, Central Kalimantan
  'po-016': [12.30, 106.90],    // Mondulkiri, Cambodia
  'po-017': [-12.83, -69.35],   // Madre de Dios, Peru
  'po-018': [-8.20, -71.10],    // Acre, Brazil
  'po-019': [1.37, 32.29],      // Uganda
  'po-020': [-18.67, 35.53],    // Mozambique
  'po-021': [-13.25, 34.30],    // Malawi
  'po-022': [-32.50, 148.50],   // NSW, Australia
  'po-023': [36.50, -120.00],   // Central Valley California
  'po-024': [19.42, -103.50]    // Jalisco, Mexico
};
for (const l of listings) {
  const c = coords[l.id];
  if (c) { l.latitude = c[0]; l.longitude = c[1]; }
}

export function getListing(slug: string): Listing | undefined {
  return listings.find((l) => l.slug === slug);
}

export function getListingById(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}

export function getFeaturedListings(): Listing[] {
  return listings.filter((l) => l.featured);
}

export const categoryLabels: Record<string, string> = {
  'nature-based': 'Nature-based',
  'engineered-removal': 'Engineered Removal',
  'renewable-energy': 'Renewable Energy',
  community: 'Community / Cookstoves'
};

export const tierLabels: Record<string, string> = {
  'prime-origins-verified': 'Prime Origins Verified',
  'self-verified': 'Self-Verified'
};
