import type { Listing } from './types';

export const listings: Listing[] = [
  {
    id: 'po-001',
    slug: 'kasigau-corridor-redd',
    projectName: 'Kasigau Corridor REDD+',
    developer: 'Wildlife Works',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0009 — Avoided Deforestation',
    projectId: 'VCS-562',
    vintage: 2023,
    country: 'Kenya',
    region: 'Taita Taveta',
    pricePerTonne: 14.5,
    tonnesAvailable: 25000,
    totalIssued: 1450000,
    bufferPoolPct: 20,
    cobenefits: ['Biodiversity', 'Community livelihoods', 'Wildlife corridor protection'],
    sdgs: [1, 8, 13, 15],
    summary: 'Protects 200,000 hectares of dryland forest between two Kenyan national parks while employing 350+ local rangers.',
    description:
      'The Kasigau Corridor REDD+ project safeguards a vital wildlife migration route connecting Tsavo East and Tsavo West National Parks. The project has reduced deforestation by over 95% in the project area and supports more than 100,000 community members through education, water, and livelihoods programs.',
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true,
    featured: true
  },
  {
    id: 'po-002',
    slug: 'climeworks-orca-dac',
    projectName: 'Orca Direct Air Capture',
    developer: 'Climeworks',
    category: 'engineered-removal',
    registry: 'Puro.earth',
    methodology: 'Geological Storage (Carbfix)',
    projectId: 'PURO-DAC-001',
    vintage: 2025,
    country: 'Iceland',
    region: 'Hellisheidi',
    pricePerTonne: 685,
    tonnesAvailable: 1200,
    totalIssued: 4000,
    cobenefits: ['Permanent storage (>10,000 years)', 'Renewable-powered'],
    sdgs: [9, 13],
    summary: 'Durable removal credits from the world\'s first commercial direct air capture and storage facility.',
    description:
      'Orca captures CO₂ directly from the atmosphere using geothermal power and mineralizes it in basalt rock via Carbfix technology, achieving permanent storage. Issuance is verified under the Puro Standard for CO₂ Removal.',
    imageUrl: 'https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true,
    featured: true
  },
  {
    id: 'po-003',
    slug: 'gyapa-cookstoves-ghana',
    projectName: 'Gyapa Improved Cookstoves',
    developer: 'ClimateCare',
    category: 'community',
    registry: 'Gold Standard',
    methodology: 'GS TPDDTEC',
    projectId: 'GS-852',
    vintage: 2024,
    country: 'Ghana',
    pricePerTonne: 12.0,
    tonnesAvailable: 48000,
    totalIssued: 2100000,
    cobenefits: ['Indoor air quality', 'Women\'s livelihoods', 'Reduced fuelwood demand'],
    sdgs: [3, 5, 7, 13],
    summary: 'Efficient cookstoves cutting charcoal use 50%+ across Ghanaian households — better health, lower emissions.',
    description:
      'Gyapa distributes locally-made efficient cookstoves that reduce charcoal consumption by 50% or more compared to traditional stoves. The project has reached over 1 million households, with verified emissions reductions and significant indoor air quality improvements.',
    imageUrl: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true
  },
  {
    id: 'po-004',
    slug: 'mai-ndombe-redd',
    projectName: 'Mai Ndombe REDD+',
    developer: 'Wildlife Works',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0007 REDD+ MF',
    projectId: 'VCS-934',
    vintage: 2022,
    country: 'DR Congo',
    pricePerTonne: 11.0,
    tonnesAvailable: 95000,
    totalIssued: 8200000,
    bufferPoolPct: 22,
    cobenefits: ['Bonobo habitat protection', 'Community health clinics', 'Schools'],
    sdgs: [1, 3, 4, 13, 15],
    summary: 'Protects 300,000 ha of Congo Basin rainforest, home to bonobos and 50,000+ community members.',
    description:
      'One of the largest REDD+ projects in the world, Mai Ndombe protects critical rainforest in the Congo Basin while delivering health, education, and agricultural support to surrounding communities.',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true
  },
  {
    id: 'po-005',
    slug: 'pacific-biochar-california',
    projectName: 'Pacific Biochar Carbon Removal',
    developer: 'Pacific Biochar',
    category: 'engineered-removal',
    registry: 'Puro.earth',
    methodology: 'Puro Biochar Methodology v3',
    projectId: 'PURO-BIO-119',
    vintage: 2025,
    country: 'United States',
    region: 'California',
    pricePerTonne: 145,
    tonnesAvailable: 6500,
    totalIssued: 18000,
    cobenefits: ['Soil health', 'Wildfire fuel reduction', 'Agricultural yields'],
    sdgs: [2, 13, 15],
    summary: 'Forest residue converted to biochar — durable carbon storage in agricultural soils across the West Coast.',
    description:
      'Pacific Biochar converts forestry residues from wildfire fuel-reduction operations into stable biochar applied to California vineyards and orchards. Storage is durable on a >100-year timescale.',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true,
    featured: true
  },
  {
    id: 'po-006',
    slug: 'rimba-raya-borneo',
    projectName: 'Rimba Raya Biodiversity Reserve',
    developer: 'InfiniteEARTH',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0007 REDD+ MF',
    projectId: 'VCS-674',
    vintage: 2023,
    country: 'Indonesia',
    region: 'Central Kalimantan',
    pricePerTonne: 16.5,
    tonnesAvailable: 32000,
    totalIssued: 3800000,
    bufferPoolPct: 20,
    cobenefits: ['Orangutan habitat', 'Peatland protection', 'All 17 SDGs validated'],
    sdgs: [1, 2, 3, 4, 5, 13, 14, 15, 17],
    summary: 'Orangutan refuge on peatland in Borneo — the first project triple-validated under all 17 SDGs.',
    description:
      'Rimba Raya protects 64,000 hectares of carbon-rich tropical peatland, providing critical refuge for endangered Bornean orangutans while delivering measurable benefits across all 17 UN Sustainable Development Goals.',
    imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true
  },
  {
    id: 'po-007',
    slug: 'gujarat-wind-india',
    projectName: 'Gujarat Wind Power',
    developer: 'Suzlon Global',
    category: 'renewable-energy',
    registry: 'Gold Standard',
    methodology: 'GS Renewable Energy v2',
    projectId: 'GS-1142',
    vintage: 2024,
    country: 'India',
    region: 'Gujarat',
    pricePerTonne: 4.8,
    tonnesAvailable: 120000,
    totalIssued: 950000,
    cobenefits: ['Rural electrification', 'Local employment'],
    sdgs: [7, 8, 13],
    summary: 'Grid-connected wind farm displacing coal generation in western India.',
    description:
      'A 200 MW wind installation in Gujarat displacing emissions from the predominantly coal-fueled Indian grid. Gold Standard certified with verified community impact.',
    imageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true
  },
  {
    id: 'po-008',
    slug: 'running-tide-kelp',
    projectName: 'Running Tide Ocean Carbon',
    developer: 'Running Tide',
    category: 'engineered-removal',
    registry: 'Puro.earth',
    methodology: 'Ocean Alkalinity & Biomass Sinking',
    projectId: 'PURO-OCN-042',
    vintage: 2025,
    country: 'Iceland',
    pricePerTonne: 240,
    tonnesAvailable: 3200,
    totalIssued: 9500,
    cobenefits: ['Ocean alkalinity restoration', 'Deep-sea storage'],
    sdgs: [13, 14],
    summary: 'Macroalgae-based ocean carbon removal with deep-sea sinking for durable storage.',
    description:
      'Running Tide grows macroalgae on biodegradable buoys seeded with alkaline limestone. The buoys sink to the deep ocean where carbon is stored on multi-century timescales while restoring ocean chemistry.',
    imageUrl: 'https://images.unsplash.com/photo-1530053969600-caed2596d242?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true
  },
  {
    id: 'po-009',
    slug: 'amazonia-pariri',
    projectName: 'Pariri Amazon Conservation',
    developer: 'Carbonext',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0015',
    projectId: 'VCS-2613',
    vintage: 2024,
    country: 'Brazil',
    region: 'Pará',
    pricePerTonne: 13.2,
    tonnesAvailable: 41000,
    totalIssued: 6700000,
    bufferPoolPct: 25,
    cobenefits: ['Indigenous land rights', 'Açaí economy', 'Jaguar habitat'],
    sdgs: [1, 10, 13, 15],
    summary: 'Indigenous-led Amazon conservation across 350,000+ hectares of primary rainforest.',
    description:
      'The Pariri project is co-developed with the Munduruku people, protecting one of the most biodiverse regions of the Brazilian Amazon while supporting traditional livelihoods.',
    imageUrl: 'https://images.unsplash.com/photo-1500354960784-987d10b03d22?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true
  },
  {
    id: 'po-010',
    slug: 'cquestr8-rock-weathering',
    projectName: 'Enhanced Rock Weathering — UK Croplands',
    developer: 'UNDO',
    category: 'engineered-removal',
    registry: 'Puro.earth',
    methodology: 'Enhanced Weathering of Silicate Minerals',
    projectId: 'PURO-ERW-014',
    vintage: 2025,
    country: 'United Kingdom',
    region: 'Scotland',
    pricePerTonne: 195,
    tonnesAvailable: 4800,
    totalIssued: 14000,
    cobenefits: ['Soil pH improvement', 'Crop yield', 'Reduced fertilizer use'],
    sdgs: [2, 13, 15],
    summary: 'Crushed basalt spread on UK farmland sequesters CO₂ as it weathers — 10,000+ year storage.',
    description:
      'UNDO spreads finely-crushed basalt on agricultural land. As the rock weathers naturally, it draws CO₂ from the atmosphere and locks it away as stable bicarbonate. Co-benefits include soil de-acidification and improved yields.',
    imageUrl: 'https://images.unsplash.com/photo-1535912559178-bb46760ad0fa?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true
  },
  {
    id: 'po-011',
    slug: 'methane-capture-landfill-texas',
    projectName: 'McCommas Bluff Landfill Methane Capture',
    developer: 'EDF Renewables',
    category: 'renewable-energy',
    registry: 'ACR',
    methodology: 'ACR Landfill Gas Destruction v1.1',
    projectId: 'ACR-380',
    vintage: 2024,
    country: 'United States',
    region: 'Texas',
    pricePerTonne: 7.5,
    tonnesAvailable: 28000,
    totalIssued: 410000,
    cobenefits: ['Methane abatement', 'Renewable natural gas'],
    sdgs: [7, 11, 13],
    summary: 'Captures methane from a Dallas landfill — converted to renewable natural gas for the grid.',
    description:
      'Methane (28× more potent than CO₂ on a 100-year basis) is captured from the McCommas Bluff landfill and converted into renewable natural gas, displacing fossil natural gas demand.',
    imageUrl: 'https://images.unsplash.com/photo-1473773386757-42beed09bb7b?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true
  },
  {
    id: 'po-012',
    slug: 'mangrove-restoration-philippines',
    projectName: 'Visayas Mangrove Restoration',
    developer: 'WorldView Impact',
    category: 'nature-based',
    registry: 'Verra',
    methodology: 'VM0033 Tidal Wetland Restoration',
    projectId: 'VCS-2876',
    vintage: 2024,
    country: 'Philippines',
    region: 'Eastern Visayas',
    pricePerTonne: 21.0,
    tonnesAvailable: 8500,
    totalIssued: 145000,
    bufferPoolPct: 30,
    cobenefits: ['Coastal protection', 'Fisheries recovery', 'Typhoon resilience'],
    sdgs: [1, 13, 14, 15],
    summary: 'Restored mangrove forests sequester carbon at high rates while protecting coastal communities.',
    description:
      'Replanting and protecting 2,400 hectares of mangrove forest in typhoon-prone coastal communities. Blue carbon storage rates 3-5× higher per hectare than terrestrial forests.',
    imageUrl: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1400&q=70',
    verified: true,
    retirementSupported: true,
    featured: true
  }
];

export function getListing(slug: string): Listing | undefined {
  return listings.find((l) => l.slug === slug);
}

export function getListingById(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}

export function getFeaturedListings(): Listing[] {
  return listings.filter((l) => l.featured);
}

export const categoryLabels: Record<string, string> = {
  'nature-based': 'Nature-based',
  'engineered-removal': 'Engineered Removal',
  'renewable-energy': 'Renewable Energy',
  community: 'Community / Cookstoves'
};
